### ISSUE TITLE
Shadow with rounded corners

### ISSUE THREAD

**Issue by Nerkyator** [IcaliaLabs/Presentr#129]
Seems that if I add shadow on presented viewController it removes rounded corners
```
presenter.dropShadow = PresentrShadow(shadowColor: .black, shadowOpacity: 0.3, shadowOffset: CGSize.init(width: 3.0, height: 3.0), shadowRadius: 5)
presenter.roundCorners = true
presenter.cornerRadius = 20.0
```
Am I missing something?

**Comment by danlozano** [comment]
Hmmm I will definitely look into this this week.

Thanks!

**Comment by danlozano** [comment]
Fixed in master.

Will send new version to cocoapods soon.

**Comment by Nickersoft** [comment]
@danlozano Currently using the latest version on Carthage and still facing this same issue.. was the fix ever released?
